# Create a GitHub action to email a report from a file at 6 a.m. daily.
name: Email report

on:
  schedule:
    - cron: "0 6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Email report
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MY_USERNAME }}
          password: ${{ secrets.MY_PASSWORD }}
          subject: Report
          body: |
            Hi,

            Please find the report attached.

            Regards,
            GitHub

          from: GitHub <